pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'harsha6798/voting-app-worker-service-ci-image:${BUILD_NUMBER}'
    }

    stages{
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/harsha-ops/Voting-App.git'
            }
            
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ./worker/"
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${DOCKER_IMAGE}"
            }
        }

        stage('Deploy to k8s') {
            steps {
                script {
                    sh '''
                    sed -i 's|image: .*$|image: ${DOCKER_IMAGE}|' ./k8s-manifest/worker-microservice-deploy.yaml
                    '''
                    sh '''
                    kubectl apply -f ./k8s/worker-microservice-deploy.yaml
                    kubectl apply -f ./k8s/worker-microservice-svc.yml
                    '''
                }
            }
        }
    }
}