apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: harsha6798/voting-app-worker-service-ci-image:7
        ports:
        - containerPort: 80